site_name: TON DEV Knowledge-base

nav: 
    - Compilers:
        - 'About': 'Compilers/About.md'
        - 'Linker CLI': 'Compilers/Linker CLI.md'
        - 'ABI Specification': 'Compilers/ABI Specification.md'
        - Solidity Compiler:
            - 'Feature Support': 'Compilers/Solidity Compiler/Solidity Support Status.md'
            - 'Using the compiler': 'Compilers/Solidity Compiler/Usage.md'
        - LLVM Compiler:
            - 'C Support Status': 'Compilers/LLVM Compiler/C Support Status.md' 
            - 'Debugging Options': 'Compilers/LLVM Compiler/Debugging Options.md'
            - 'Compiling C': 'Compilers/LLVM Compiler/Compiling and Deploying C Contracts.md' 

    - SDK:
        - 'Overview': 'SDK/Overview.md'
        - 'Installation': 'SDK/Installation.md'
        - 'Local Node': 'SDK/Local Node.md'
        - 'TONDEV CLI': 'SDK/TONDEV CLI.md'
        - Using Client Libraries:
            - 'Library Modules': 'SDK/Client Libraries/Library Modules.md'
            - 'Rust': 'SDK/Client Libraries/Using Libraries/Rust.md'
            - 'JavaScript': 'SDK/Client Libraries/Using Libraries/Node.js.md'
        
        - Misc:
            - 'Getting Logs': 'SDK/Auxiliaries/Getting Logs.md'
            - 'Troubleshooting': 'SDK/Auxiliaries/Troubleshooting.md'
            - 'Installing Ubuntu VM': 'SDK/Auxiliaries/Installing Ubuntu VM.md'
    - FAQ: 'FAQ.md' 
      
    - TON Blockchain:
        - 'TVM Error Codes': 'TON Blockchain/TVM Error Codes.md'
        - 'TON Whitepaper': 'TON Blockchain/TON Specifications/TON Whitepaper.md'
        - 'TON Virtual Machine': 'TON Blockchain/TON Specifications/TON Virtual Machine.md'
        - 'TON Blockchain': 'TON Blockchain/TON Specifications/TON Blockchain.md'
        - 'Lite Client Guide': 'TON Blockchain/TON Specifications/Lite Client Guide.md'
    - 'Smart Contract Lore':
        - 'ABI Specification V1': 'Smart Contract Lore/ABI Specification New.md'
        - 'ABI Specification V0': 'Smart Contract Lore/ABI Specification.md'
        - 'Key Generation and Use': 'Smart Contract Lore/Key Generation and Use.md'
        - 'Gas and Storage': 'Smart Contract Lore/Gas Calculation Basics.md'
        - 'Replay Attack Protection': 'Smart Contract Lore/Replay Attack Protection.md'
         
    - Glossary: 'Glossary.md'
    - Release notes:
           - 'Archive 2019': 'Release Notes Archive.md'

theme:
    name: mkdocs
    custom_dir: custom_dir/

    
