site_name: TON DEV Knowledge-base

nav: 
    - Compilers:
        - 'About': 'Compilers/About.md'
        - 'Linker CLI': 'Compilers/Linker CLI.md'
        - 'ABI Specification': 'Compilers/ABI Specification.md'
        - Solidity Compiler:
            - 'Reference Guide': 'Compilers/Solidity Compiler/Reference Guide.md'
            - 'Feature Support': 'Compilers/Solidity Compiler/Solidity Support Status.md'
            - 'Usage': 'Compilers/Solidity Compiler/Usage.md'
        - LLVM Compiler:
            - 'C Support Status': 'Compilers/LLVM Compiler/C Support Status.md' 
            - 'Debugging options': 'Compilers/LLVM Compiler/Debugging options.md' 

    - SDK:
        - 'Overview': 'SDK/Overview.md'
        - 'Installation': 'SDK/Installation.md'
        - Client Library Modules:     
            - 'Modules Overview': 'SDK/Client Libraries/Library Modules/Overview.md'
            - 'Contracts': 'SDK/Client Libraries/Library Modules/Contracts.md'
            - 'Queries': 'SDK/Client Libraries/Library Modules/Queries.md'
            - 'Crypto': 'SDK/Client Libraries/Library Modules/Crypto.md'
        - Using Client Libraries:
            - 'Rust': 'SDK/Client Libraries/Using Libraries/Rust.md'
            - 'JavaScript': 'SDK/Client Libraries/Using Libraries/Node.js.md'
        - Local Node:
            - 'Local Node': 'SDK/Local node/Local Node.md'
            - 'Node SE Giver': 'SDK/Local node/Node SE Giver.md'
        - Misc:
            - 'Getting Logs': 'SDK/Auxiliaries/Getting Logs.md'
            - 'TON SDK CLI': 'SDK/Auxiliaries/TON SDK CLI.md'
            - 'Troubleshooting': 'SDK/Auxiliaries/Troubleshooting.md'
            - 'Installing Ubuntu VM': 'SDK/Auxiliaries/Installing Ubuntu VM.md'
    - FAQ: 
        - 'Smart Contracts': 'FAQ/Smart Contracts.md'
        - 'SDK and Integration': 'FAQ/SDK and Integration.md'
        - 'Solidity Compiler': 'FAQ/Solidity Compiler.md'
        - 'TON and TVM': 'FAQ/TON and TVM.md'
    - TON Blockchain:
        - 'Gas Price Basics': 'TON Blockchain/Gas Calculation Basics.md'
        - 'Replay Attack Protection': 'TON Blockchain/Replay Attack Protection.md'
        - 'Storage Fee Calculation': 'TON Blockchain/Storage Fee Calculation.md'
        - 'TVM Error Codes': 'TON Blockchain/TVM Error Codes.md'
        - TON Specifications:
            - 'TON Whitepaper': 'TON Blockchain/TON Specifications/TON Whitepaper.md'
            - 'TON Virtual Machine': 'TON Blockchain/TON Specifications/TON Virtual Machine.md'
            - 'TON Blockchain': 'TON Blockchain/TON Specifications/TON Blockchain.md'
            - 'Lite Client Guide': 'TON Blockchain/TON Specifications/Lite Client Guide.md'
    - Glossary: 'Glossary.md'
    - Release notes: 'Release Notes'

    